# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  # Manually trigger the workflow
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    # use uv
    - name: Install uv
      uses: astral-sh/setup-uv@v5
    
    # sync
    - name: Sync uv
      run: uv sync

    # run main.py
    - name: Run main.py
      run: uv run main.py
      env:
        MONGO_URI: ${{ secrets.MONGO_URI }}
